### ISSUE TITLE
Update for Processing 3

### ISSUE THREAD

**Issue by shiffman** [diwi/diewald_fluid#1]
Hello!

I'm planning on doing a video tutorial about fluid simulation.  I am going to implement the navier-stokes algorithm from scratch in Processing, but thought I would also show your library.  Are you interested in updating it for Processing 3?  The CPU examples still run with some minor tweaks, but the GPU ones would have to be updated to use the new PShader API (I think).   I would be glad to help / submit a pull request!

Dan

**Comment by diwi** [comment]
Hi Dan,

Im currently working on updating it to Processing 3. It will take some days until it will be finished because i want to add some functionality that was missing in this older library.

Best, Thomas

**Comment by shiffman** [comment]
Great, please let me know if I can help!  And here's the info about how to publish when it is ready:

https://github.com/processing/processing/wiki/Library-Basics#advertising-your-library

**Comment by diwi** [comment]
Hi Dan,

the "updated" version is finally released here

https://github.com/diwi/PixelFlow

It's a completely new library and not compatible width this one.
The example folder contains around 20 examples (basic to advanced) that should make the first steps a bit easier. Most need controlP5 (GUI Library) and some the Processing Video Library.

best, Thomas

**Comment by shiffman** [comment]
Wonderful!  Have you been in touch with @prisonerjohn about getting it listed in the contributions manager?

**Comment by diwi** [comment]
I tried to email him, using the adress from here:
https://github.com/processing/processing/wiki/Library-Basics#advertising-your-library

... but i'm not sure if he received it yet.
